### ISSUE TITLE
Add a server-side command to clear the index cache

### ISSUE THREAD

**Issue by gabro** [scalameta/language-server#109]
Sometimes it's necessary to clear the index cache (see for instance https://github.com/scalameta/language-server/pull/105#issuecomment-350539729). This command must be executed on the server, since the client doesn't know the cache location (which is machine-dependent). It's also a good opportunity to learn about [`workspace/executeCommand`](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#workspace_executeCommand).

**Comment by laughedelic** [comment]
I'm not sure I understand why should the client take care of this?

**Comment by gabro** [comment]
What do you mean by "take care"? The idea is that the client asks the server to perform this action through the `workspace/executeCommand` request and the server executes it.

In general the idea is to have a simple way to debug issues with the indexing, and I think having a command inside the editor is convenient while developing the server or beta-testing it.

**Comment by laughedelic** [comment]
Yep, I also read the chat and now I understand. I just missed the context, that it's for debugging purposes.

**Comment by gabro** [comment]
👍 Yes, it's for debugging and beta-testing purposes. We could probably put this under a "debug" build or something and not include them in a "production" release. That said, that's a very early concern :D
