### ISSUE TITLE
-Dvscode.workspace= should be removed

### ISSUE THREAD

**Issue by olafurpg** [scalameta/language-server#112]
Or it should default to the current working directory. This would make it easier to use `coursier bootstrap -o metaserver` since the workspace can be passed dynamically on start. Related #111

**Comment by gabro** [comment]
By the way, the language server communicates the workspace path at initialization. The only usage of the workspace directory before the server has started is for logging, but we can easily work around that. I think we should remove the workspace parameter entirely.

**Comment by olafurpg** [comment]
I see, cool, then we should default to working directory `.metaserver/*`. We should keep the compilerconfig files there too IMO. Question if we should rename metaserver to something better before doing this?

**Comment by gabro** [comment]
I think that's ok keeping the name for now. I don't think it will be such a breaking change if we rename it in the future.

**Comment by olafurpg** [comment]
OK, cool, are y'all ok with using `.metaserver/*`? I think `target/` is quite sbt specific and doesn't play nicely with other build tools.

**Comment by gabro** [comment]
Sure, I think `.metaserver` is good enough for the time being.

**Comment by laughedelic** [comment]
Do you mean `~/.metaserver`? I thinks it's ok, but I would also suggest to follow the same way as with cache directories, i.e. use XDG and other analogous conventions on each system.

**Comment by gabro** [comment]
I think @olafurpg means `<projectWorkspace>/.metaserver`, since it contains project-specific stuff such as the server logs.

**Comment by olafurpg** [comment]
That's a good idea @laughedelic we should use the `directories` library to follow conventions of every OS. For the logs/.compilerconfig files we store it per-workspace.
