### ISSUE TITLE
workspace/symbols

### ISSUE THREAD

**Issue by olafurpg** [scalameta/language-server#114]
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#workspace_symbol

The workspace symbol request is sent from the client to the server to list project-wide symbols matching the query string.

Request:

```ts
method: 'workspace/symbol'
params: WorkspaceSymbolParams defined as follows:
/**
 * The parameters of a Workspace Symbol Request.
 */
interface WorkspaceSymbolParams {
	/**
	 * A non-empty query string
	 */
	query: string;
}
```

I'd like to try and use mtags alone for this, since that would enable workspace/symbols to work without any semanticdb/build integration.

**Comment by olafurpg** [comment]
Some questions:

- Should we add *.scala files to the watcher so that we can syntactically index new files as they come with for example git checkout?
- Should we only include globally accessible trait/class/object? That's the IntelliJ behavior and I personally like it. I'm afraid adding methods may create too much noise, but maybe it's not a problem.

**Comment by olafurpg** [comment]
Another question, should this include indexed symbols in the classpath? In IntelliJ non-project symbols are opt-in with Cmd+N

<img width="392" alt="screen shot 2017-12-18 at 22 05 36" src="https://user-images.githubusercontent.com/1408093/34128042-a5e81c2a-e43f-11e7-9b04-f26e1790a157.png">

**Comment by olafurpg** [comment]
https://github.com/scalameta/language-server/compare/master...olafurpg:workspace-symbols?expand=1 contains boilerplate for workspace/symbols, implementation is still WIP

**Comment by gabro** [comment]
Done in #140
