### ISSUE TITLE
Hover and definition on comments

### ISSUE THREAD

**Issue by laughedelic** [scalameta/language-server#136]
<img width="609" alt="screen shot 2017-12-17 at 16 45 45" src="https://user-images.githubusercontent.com/766656/34082630-1cf9b23a-e362-11e7-96d1-5a2383ce24ef.png">

Language server says that @olafurpg is a `meta.Traverser` 😝 

It seems that type on hover on comments returns the type of the enclosing block of code. Definition results are even more strange, because they are different at different times (I can record a demo if needed).

**Comment by olafurpg** [comment]
I think might be yet another good reason to move to semanticdb for hover, repeating https://github.com/scalameta/language-server/issues/125#issuecomment-351956818

**Comment by olafurpg** [comment]
Should be fixed in #148, we use semanticdb for hover now instead of the presentation compiler.
