### ISSUE TITLE
Get rid of `implicit val format = Json.format[T]` boilerplate

### ISSUE THREAD

**Issue by olafurpg** [scalameta/language-server#153]
We should use something like https://github.com/kifi/json-annotation to reduce boilerplate

**Comment by gabro** [comment]
As discussed offline, we could also just move to circe and use its `@JsonCodec` annotation for semi-auto derivation. The choice of play-json is currently bound to the json-rpc library we're using, but that will probably go away soon.

**Comment by olafurpg** [comment]
Fixed in #165
