### ISSUE TITLE
Default scalafix settings

### ISSUE THREAD

**Issue by olafurpg** [scalameta/language-server#16]
By default, scalafix complains about the lack of .scalafix.conf because it doesn't know which rules to enable. Should we enable some set of rules by default?

**Comment by gabro** [comment]
I was thinking about this, but I'm not sure on how users would opt-out then.

I would ideally run scalafix only if `.scalafix.conf` is found in the workspace and allow users to explicitly disable it entirely in the extension config (related: #6).

**Comment by laughedelic** [comment]
Can we determine on the server side whether the project has scalafix enabled? I think that showing a warning about its config when scalafix is not even present doesn't make much sense. On the other hand, if user has already enabled scalafix and is using this server/plugin, obviously he want scalafix to be integrated. I think that scalafix itself should have some reasonable defaults out of the box, like other linters do.

> I was thinking about this, but I'm not sure on how users would opt-out then.

I think that the client could use the VS Code configuration/settings for this. Plus LSP has some requests for dynamically registering/[unregistering](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#new-unregister-capability) capabilities

**Comment by olafurpg** [comment]
We can remove the warning in https://github.com/scalameta/language-server/blob/08d394283c41c55b514a194eb9a660c309e199f2/language-server/src/main/scala/scala/meta/languageserver/Linter.scala#L102-L105 Then we don't run scalafix unless there is a .scalafix.conf file.

**Comment by gabro** [comment]
> Can we determine on the server side whether the project has scalafix enabled? I think that showing a warning about its config when scalafix is not even present doesn't make much sense.

I agree. I would just like to point out that when using `language-server` scalafix is already included. The user just needs to provide a `.scalafix.conf` and it starts working. No additional installation is required, other than the `semanticdb-scalac` compiler plugin.

So I think detecting the `.scalafix.conf` is a good way of deciding whether to run it or not, and we can also add an explicit setting in the future.

**Comment by laughedelic** [comment]
> I would just like to point out that when using language-server scalafix is already included.

Oh! I was confused about it, hence my comment about the setup instructions: https://github.com/scalameta/language-server/pull/14#discussion_r149689098. Now I also agree that presence config is a good indicator.

But how do you actually use/activate Scalafix in VS Code?

**Comment by olafurpg** [comment]
Fixed in #25
