### ISSUE TITLE
Integrate with sbt v1.1 server

### ISSUE THREAD

**Issue by olafurpg** [scalameta/language-server#169]
See announcement: https://developer.lightbend.com/blog/2017-11-30-sbt-1-1-0-RC1-sbt-server/index.html

It would be fun to try and detect when sbt server is running and send sbt/exec notifications on buffer save and forward diagnostics to the client. Might also be interesting to try and replace scalametaEnableCompletions.

A feature I'm personally quite interested in is test on save, I use `~foo/testOnly com.blah.Foo` all the time. It would be nice if the editor could instead trigger tests without using file watching.

**Comment by gabro** [comment]
Yes, this is super cool! We can detect the presence of the `active.json` file and become clients ourselves. For instance showing compiler errors directly from sbt would be an interesting integration with the presentation compiler ones.
