### ISSUE TITLE
Consider using sbt-release-early

### ISSUE THREAD

**Issue by laughedelic** [scalameta/language-server#28]
Now that you've setup Travis CI, what do you think about using [scalacenter/sbt-release-early](https://github.com/scalacenter/sbt-release-early)? I guess you know this project well and I don't need to explain why it's useful, but I also understand that you may not want to use right now while things are moving too fast.

**Comment by gabro** [comment]
I agree that's a sensible way of releasing artifacts.

I would be ok in setting this up and hold on onto publishing until we're ready.

**Comment by olafurpg** [comment]
I can configure the CI a release on tag push once we're ready to publish this plugin. For now I prefer to wait with publishing a bit longer until we've solved issues like reusing symbol indices across editor sessions, reporting red squigglies, build semanticdbs on the fly with the presentation compiler to supporting "go to definition" for unsaved buffers.

**Comment by laughedelic** [comment]
Although I understand that you don't want to make unstable stuff available for wide audience, I'd still really like to have at least "snapshots" (commit-sha-versioned) published (even temporarily) to some bintray repo (by CI), because publishing locally is very limiting (also from my editor-plugin-developer perspective 😅)

**Comment by olafurpg** [comment]
I see @laughedelic makes sense. I can try to setup publish to the scalameta bintray on merge.

**Comment by laughedelic** [comment]
Thanks! I can help with setting up the plugin, if you want.

**Comment by olafurpg** [comment]
That would be awesome! Do you have a bintray account? I can give you publish rights for the Scalameta bintray org. Alternatively, feel free to configure it to publish to your personal bintray if you're ok with that. I've made you an admin to this repo so you should be able to set secrets in Travis, if not let me know.

**Comment by laughedelic** [comment]
Oh, wow! 😄 Cool, I'll try to setup everything then.

> Do you have a bintray account?

Sure: https://bintray.com/laughedelic

**Comment by olafurpg** [comment]
You've got an invite! Let me know if you have problems publishing with your API key :)

**Comment by laughedelic** [comment]
OK, thanks 👍
