### ISSUE TITLE
Load all .semanticdb files at start

### ISSUE THREAD

**Issue by gabro** [scalameta/language-server#3]
Scenario:

- user compiles a project
- user closes the project
- user opens the project

Expected result:
- the language-server features still work

Actual result:
- the language-server features won't work until a clean/compile (because semanticdb files are only read when produced/changed)

A simple solution is to try search for a semanticdb file on `textDocument/open` or even to get them all when the server starts and feed them to the semanticdbs monix observable.

**Comment by olafurpg** [comment]
Fixed in #8 ?

**Comment by gabro** [comment]
Yep!
