### ISSUE TITLE
SymbolKind for val should not be constant

### ISSUE THREAD

**Issue by olafurpg** [scalameta/language-server#39]
User is `val` (icon is kinda ugly in vscode with https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline)
<img width="187" alt="screen shot 2017-11-19 at 17 54 00" src="https://user-images.githubusercontent.com/1408093/32993035-b18579b4-cd52-11e7-8dc2-d23e1d72cc46.png">

User is `var`
<img width="179" alt="screen shot 2017-11-19 at 17 54 06" src="https://user-images.githubusercontent.com/1408093/32993036-b19f9920-cd52-11e7-8f9c-f365797d596e.png">

I feel that constant is not appropriate for vals since vals can be very stateful objects, constants are IMO literals like `"string"` and `2`

**Comment by laughedelic** [comment]
For literals there are `SymbolKind`s like `String`, `Number`, `Boolean`, `Array`.

I think that `SymbolKind`s don't map well on the entities in Scala, but we should try to use more of them just for visual distinction. Here's how `val` vs. `var` looks in Atom:

<img width="144" alt="screen shot 2017-11-19 at 18 19 32" src="https://user-images.githubusercontent.com/766656/32993344-fe4f2444-cd56-11e7-8582-26317f78c137.png">

I think it kind of makes sense and would be wrong to mark both `val` and `var` with the same kind/icon. Icons design is, of course, something editor-specific and could be improved, but the set of symbol kinds is a part of LSP and is harder to change, I think.

**Comment by laughedelic** [comment]
Also, here is the full list of symbols/icons in the two editors:

<img height="500" alt="screen shot 2017-11-14 at 01 08 14" src="https://user-images.githubusercontent.com/766656/32993387-a1364ce6-cd57-11e7-819a-eeff38e23989.png"> <img height="500" alt="screen shot 2017-11-14 at 18 58 06" src="https://user-images.githubusercontent.com/766656/32993391-a87b93e4-cd57-11e7-87e6-bfb8f4c03df4.png">

**Comment by ShaneDelmore** [comment]
I would have thought Constant meant single assignment, but it sounds like @olafurpg has the intuition that Constant means literal.  They seem to already have icons for String, Number, and Boolean which would cover a good deal of @olafurpg interpretation of Constant (wouldn’t it?) but I don’t see anything else available that covers a single assignment value.  Of these admittedly not wonderful options I prefer Constant still, but is it worth proposing another symbol kind to LSP?  As for icons, that feels unrelated, we can always contribute better icons.

**Comment by ShaneDelmore** [comment]
For what it’s worth, I like the atom icons, visually one looks like it changes over time, and the other looks like it is assigned once to my eye.

**Comment by olafurpg** [comment]
I guess I'm just unhappy with the icon for outline types in the vscode plugin for "Constant", in atom it looks more sensible. I agree we should have a different symbol kind of vars and vals.

**Comment by laughedelic** [comment]
Check https://github.com/patrys/vscode-code-outline/issues/4 and https://github.com/Microsoft/vscode/issues/28592: the imcons have to be iproved in the VSCode itself. I tried to search a bit related issues in the vscode repo and I got an impression that it's not considered an big problem.. 🙁
Also related: https://github.com/Microsoft/vscode/issues/2628 (didn't read completely, but it's about having more kinds) and https://github.com/Microsoft/vscode/issues/23927 (about modifiers for symbol kinds)

**Comment by olafurpg** [comment]
I can live with it 😸
