### ISSUE TITLE
ctags indices redundantly include source file contents

### ISSUE THREAD

**Issue by olafurpg** [scalameta/language-server#44]
The ctags indices currently store the full file contents of all sources in your classpath. There is no need for that since we can store just the paths to the entries in the zip/jar files instead.

**Comment by olafurpg** [comment]
a relevant line of code is here https://github.com/scalameta/language-server/blob/617d8644922f379f0d0a874c679aaa04347c92f5/metaserver/src/main/scala/scala/meta/languageserver/compiler/ScalacProvider.scala#L97 where we store the database. The database we pass to leveldb should have the .contents field set to `""`. 

SymbolIndexerTest should run the entire pipeline, but make sure to clean your global leveldb cache ;)

**Comment by ShaneDelmore** [comment]
I am going to have to dig deeper into how the SymbolIndexer works.  I see no version of this so far that doesn't cause the SymbolIndexer tests to fail with Symbol not found.

**Comment by ShaneDelmore** [comment]
Database doesn't really have contents as far as I can see, each document has contents.  If I map the contents to "" for each document the SymbolIndexer fails.  I see various Input types, VirtualFile, File, Synthetic, etc.. but no documentation on when each should be used.  @olafurpg Do you know if I need to change the Input type of each document, and not just set the content = ""?

**Comment by ShaneDelmore** [comment]
If I am understanding this issue correctly the best course of action would be to just use the raw Input type instead of always coercing it to Input.VirtualFile.  Does that feel like a reasonable assessment?

**Comment by ShaneDelmore** [comment]
Digging deeper the core issues with SymbolIndexer may be due to trying to use the contents of the virtual file to find the offset using def offsetToLine which I would expect to be incorrect if I just set the contents of the virtual file = "".  If this is the only usage then storing the positions in the needed format the first time we read the file may be enough to resolve this without resorting to re-opening the files from jars.

**Comment by ShaneDelmore** [comment]
Keeping a prefix sum table to help translate between absolute offset and line/character would get around storing the actual content and still enable symbol lookup to work.  https://en.wikipedia.org/wiki/Prefix_sum

**Comment by olafurpg** [comment]
@ShaneDelmore indeed, we need the file contents to do line/column/offset translations. The way I imagined this would work is that

- before persisting, remove `Documnet.contents`
- when loading, read `Documnet.filename` (which will be a uri, see `org.langmeta.internal.io.FileIO.readAllBytes(URI)`) and put the contents back into the document

We may need to replace the `getOrElseUpdate` call with a utility that populates `.contents` like that. We should probably move `createFileInWorkspaceTarget` into a method in some `ClasspathIndexing` object in the `search` package. The call to `documentSubscriber.onNext` can be replaced with a callback on a function passed to the method.

**Comment by ShaneDelmore** [comment]
I am going to put this on hold for now until I have a large number of semantic dbs loaded up to be able to test the tradeoff between space used in leveldb and unzipping jars and semanticdbs to load them.

**Comment by olafurpg** [comment]
This has not shown to be a big performance concern, let's close this ticket and reopen later if it is indeed an issue.
