### ISSUE TITLE
Move completions to new compiler testing infrastructure

### ISSUE THREAD

**Issue by olafurpg** [scalameta/language-server#59]
In #51  and #55 we moved signatureHelp and hover to a new testing infrastructure. This new infrastructure makes it very productive to polish the output from the presentation compiler using `~metaserver/testOnly -- tests.compiler`. This workflow is way more productive than doing `publishLocal`, open vscode, manually type code and see what it produces.

The completion provider can also benefit from some polishing in how the completions are ordered, for example that fields of a class take prioritity over defaults like `toString`/`finalize`

**Comment by olafurpg** [comment]
PS. I've started working on this.

**Comment by olafurpg** [comment]
Actually, would someone be interested in working on this? I have a WIP diff here https://github.com/scalameta/language-server/compare/master...olafurpg:completions?expand=1 that can be used as a base. There are other issues I can work on instead, for example building semanticdbs on the fly with the presentation compiler.

**Comment by gabro** [comment]
I can work on this. I've already started to hack around with completion priorities a few days ago, so I have a vague idea of how to tackle this.

**Comment by olafurpg** [comment]
Awesome! Just realised why completions started crashing a lot now, I removed the `_CURSOR_` trick in the signatureHelp PR. Adding `_CURSOR_` avoids many parse errors and enables completions on parts like `User.<COMPLETE>`

https://github.com/scalameta/language-server/pull/51/commits/fe144332132f40885d2964f3d76a854829b55ea6#diff-be76cbaabee1e6378859da7ffe659ab1L60

We should probably add `_CURSOR_`  in `Compiler.addCompilationUnit`, even if that's used for more than completions.

I suspect with this change we can avoid this hacky catch here

https://github.com/scalameta/language-server/blob/b160931177b6d9d0d351ec364cfbca70669fba08/metaserver/src/main/scala/scala/meta/languageserver/compiler/CompilerUtils.scala#L15

**Comment by gabro** [comment]
I'm not sure I understand the `_CURSOR_` trick, but is it just to make sure the parser doesn't fail when completing at the end of a line?

> We should probably add `_CURSOR_` in Compiler.addCompilationUnit, even if that's used for more than completions.

`addCompilationUnit` as no offset in input, where should we add the `__CURSOR__`?

**Comment by gabro** [comment]
Ah, nvm, got it. I think your intuition is right, I've added it back and it seems to be working. I'll push it to a branch soon.

**Comment by gabro** [comment]
Scratch that, it seems to have no effect :(
