### ISSUE TITLE
Sort completion items by relevance

### ISSUE THREAD

**Issue by gabro** [scalameta/language-server#63]
Currently completion items are sorted alphabetically.

Ideally we would want them sorted by relevance, where relevance can be a combination of multiple factors, such as (but not limited too):

- inheritance
- visibility
- locality

**Comment by ShaneDelmore** [comment]
I would add usage if we can figure that out quickly.   If I happen to be in a project that uses scalaz.Future in nearly every file, then I am less likely to want to use scala.Future for example.
