### ISSUE TITLE
textDocument/references

### ISSUE THREAD

**Issue by olafurpg** [scalameta/language-server#70]
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_references

> The references request is sent from the client to the server to resolve project-wide references for the symbol denoted by the given text document position.

The data already exists in `SymbolIndex`, but the server needs to register this capability and listen to those requests. This commit here https://github.com/scalameta/language-server/pull/51/commits/fe144332132f40885d2964f3d76a854829b55ea6 can give an idea how to add support for new capabilities.

**Comment by laughedelic** [comment]
I'd like to try it, if nobody has started yet.
