### ISSUE TITLE
Invalid params on completionItem/resolve

### ISSUE THREAD

**Issue by gabro** [scalameta/language-server#81]
When using in VSCode, the output channel of the extension is full of

```
[Error - 4:50:59 PM] Request completionItem/resolve failed.
  Message: Invalid params
  Code: -32602 
[object Object]
```

There's probably something wrong with the `languageserver` bindings

**Comment by laughedelic** [comment]
`languageserver` doesn't implement `completionItem/resolve` request. Looking at the [spec](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#completion-item-resolve-request) I don't even understand what it's supposed to return:

> The request is sent from the client to the server to resolve additional information for a given completion item.

Anyway, I think we just set the completion-related capability wrong. Try changing `resolveProvider` to `false` here and see if you'll still get those errors:

https://github.com/scalameta/language-server/blob/b60f7b830a9d88471c39fec61aac41fd7d8f55b3/metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala#L102-L107

**Comment by gabro** [comment]
Ah good catch, I'm on it, I'll report back soon

--
Gabriele
