### ISSUE TITLE
Red squigglies

### ISSUE THREAD

**Issue by olafurpg** [scalameta/language-server#84]
A key feature that is currently missing is red squigglies for compile errors. I've been hesitant to switch on the error messages from the presentation compiler in fear of reporting false negatives by stale/incorrect classpaths (I'm scarred by false negatives in IntelliJ). However, I think red squigglies from the presentation compiler can help surface integration issues when the classpath/setup is stale/broken.

Open question: should we run the compiler on file save on every keystroke?

We can run on every keystroke here
https://github.com/scalameta/language-server/blob/d600fc0881cd19600132a7ee3b6a234c8557e1f9/metaserver/src/main/scala/scala/meta/languageserver/ScalametaLanguageServer.scala#L172-L180

We could create an Observable[FileChanged] where something like `case class FileChanged(uri: String, contents: String)` that gets then mapped through the presentation compiler with something like

```scala
askLoadedTyped(unit).get
unit.problems.map(toLSPDiagnostic).foreach(notifications.publishDiagnostics)
Effects.CompilerNotifications
```
Similar to how scalafix linter messages get reported.

**Comment by gabro** [comment]
> Open question: should we run the compiler on file save on every keystroke?

I would start with every keystroke and fallback to on-save in case it becomes annoying.

Also, we can debounce the Observable to run it only when the user takes a break from typing.

**Comment by gabro** [comment]
Done in #100 (we'll probably iterate on that, but the basic functionality is there)
