### ISSUE TITLE
Hover provider

### ISSUE THREAD

**Issue by gabro** [scalameta/language-server#9]
For names that have a matching symbol this should be easy.

@xeno-by / @olafurpg how far away are we from having type-at-point support in scalameta? 😇

**Comment by olafurpg** [comment]
I think Denotation.signature will do a decent job for type-at-point. It won't resolve the type as seen from the call-site (`map` in `List(1).map(...)` won't take into account `List[Int]` prefix) but I think the raw signature is a lot better than nothing at all.

**Comment by gabro** [comment]
Speaking of `Denotation.signature`, as suggested in #2 [`textDocument/signatureHelp`](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_signatureHelp) looks within reach too!

(It would also be great to have scaladoc for methods and classes in semanticdb, but I've no idea of the difficulty)

**Comment by olafurpg** [comment]
Uncompiled scaladocs (no resolution of `[[Name]]`) are probably quite easy to support, I have an implementation that maps docstring tokens to definitions that we can probably run inside semanticdb-scalac.
